### ISSUE TITLE
Let's move 

### ISSUE THREAD

**Issue by mosch** [allthings/node-sdk#82]
I found it quite confusing to find this repository called **node-sdk**, but the npm package being called **allthings/sdk**. I'd suggest we also move this repository.

**Comment by adieuadieu** [comment]
_Sorry about the label mixup.. Tried to add `discussion` label, but seems Github is still messed up after it's outage._

The thinking behind the name was that, in the future we may have SDKs for other languages. From a little looking around, I found that a common pattern in the community for this situation seems to be to prefix (or append) the repo with it's target ecosystem, e.g. `node-xyz` or `haskell-xyz`, or or `go-xyz`. 

The thinking for the NPM package `@allthings/sdk` was that NPM _is_ for the Node ecosystem, and calling it `@allthings/node-sdk` would be redundant and slightly weird.

**Comment by mosch** [comment]
I understand the motivation however I still expect to have the a relation between the package name and repository name – to me this is more important avoiding the redundancy of `@allthings/node-sdk`. Browsing the allthings/node-sdk on Github I just expect the package to have the same name.

**Comment by adieuadieu** [comment]
I feel that linking the NPM package `@allthings/sdk` to the github `allthings/sdk` repo is Node/JS-ecosystem-centric. What will we call the repository for the Java SDK?

Here's a random sampling of what others do (via most popular packages [here](https://www.npmjs.com/search?q=sdk&ranking=popularity&page=0&perPage=1000).

`npm install stripe` --> https://github.com/stripe/stripe-node
`npm install aws-sdk` --> https://github.com/aws/aws-sdk-js
`npm install mixpanel` --> https://github.com/mixpanel/mixpanel-node
`npm install @slack/client` --> https://slackapi.github.io/node-slack-sdk/
`npm install paypal-rest-sdk` --> https://github.com/paypal/PayPal-node-SDK
`npm install dropbox` --> https://github.com/dropbox/dropbox-sdk-js
`npm install mapbox` --> https://github.com/mapbox/mapbox-sdk-js
`npm install apiai` --> https://github.com/dialogflow/dialogflow-nodejs-client

**Comment by mosch** [comment]
`What will we call the repository for the Java SDK?`
**java-sdk**

Good to see how a lot of these companies name their sdks, however I think the more important pattern to apply here is the npm standard of having _repository name_ = _npm package name_  whenever possible

**Comment by adieuadieu** [comment]
I think that pattern holds true only when the package is a project for which there is only a single ecosystem implementation (e.g. nodejs). We also have to be careful of our biases towards the node ecosystem with our assumptions regarding that pattern.

There are many popular packages/repositories which make me think the pattern _repository name = npm package name_ is not as clear-cut in our context:

https://github.com/nodejitsu/node-http-proxy
https://github.com/kelektiv/node-uuid
https://github.com/isaacs/node-glob
https://github.com/jprichardson/node-fs-extra
https://github.com/peterbraden/node-opencv
https://github.com/felixge/node-formidable
https://github.com/bitinn/node-fetch
https://github.com/mapbox/node-sqlite3
https://github.com/dresende/node-orm2
https://github.com/oauthjs/node-oauth2-server
https://github.com/spdy-http2/node-spdy
https://github.com/adaltas/node-csv
https://github.com/visionmedia/node-progress
https://github.com/lloyd/node-memwatch
https://github.com/mscdex/node-imap
https://github.com/archiverjs/node-archiver
https://github.com/tediousjs/node-mssql
https://github.com/evanw/node-source-map-support
https://github.com/rvagg/node-worker-farm
https://github.com/js-platform/node-webrtc
https://github.com/dodo/node-slug
https://github.com/node-tensorflow/node-tensorflow
https://github.com/pgriess/node-webworker
https://github.com/atom/node-keytar
https://github.com/gomfunkel/node-exif
https://github.com/ranisalt/node-argon2
https://github.com/kriasoft/node-sqlite
https://github.com/felixge/node-stack-trace
https://github.com/damianociarla/node-ffmpeg
https://github.com/felixge/node-ar-drone
https://github.com/felixge/node-combined-stream
https://github.com/felixge/node-graphite
https://github.com/felixge/node-dirty
https://github.com/tritech/node-icalendar
https://github.com/kapouer/node-webkitgtk
https://github.com/blueimp/node-ffmpeg-image-diff
https://github.com/NodeRedis/node_redis
https://github.com/auth0/node-jsonwebtoken
https://github.com/restify/node-restify
https://github.com/mongodb/node-mongodb-native
https://github.com/googleapis/google-api-nodejs-client
https://github.com/brianc/node-postgres
https://github.com/sass/node-sass
https://github.com/trentm/node-bunyan
https://github.com/Automattic/node-canvas
https://github.com/nodejs/node-gyp
https://github.com/kelektiv/node.bcrypt.js
https://github.com/nodegit/nodegit
https://github.com/rchipka/node-osmosis
https://github.com/lorenwest/node-config
https://github.com/jscs-dev/node-jscs
https://github.com/kelektiv/node-cron


SASS is a good example of what I mean about our nodejs bias:
SASS for Node: `npm install sass`, repo: https://github.com/sass/node-sass
SASS for Ruby:  `gem install sass`, repo: https://github.com/sass/ruby-sass

Stripe's SDK is another example:
Stripe for Node: `npm install stripe`, repo: https://github.com/stripe/stripe-node
Stripe for Ruby: `gem install stripe`, repo: https://github.com/stripe/stripe-ruby
Stripe for Python: `pip install stripe`, repo: https://github.com/stripe/stripe-python

And, for a look at another ecosystem's package manager, let's take Rust:
This crate (Rust version of npm package) https://crates.io/crates/serde has the same create-to-repo pattern as npm-to-repo pattern: https://github.com/serde-rs/serde

Or, Elixir: https://hex.pm/packages/poison --> https://github.com/devinus/poison

Then it would seem that the pattern _repository name = package name_ only applies to projects where there is only a single ecosystem involved. The pattern results in a repo naming conflict given more than 1 ecosystem.

**Comment by mosch** [comment]
Wow, since you did a lot of well-founded research it seems the package name is a thing for you 👍 I'd prefer to have a good ergonomic for each platform rather than consistency or redundancy in naming – this is why I'd prefer something like: 

yarn add `@allthings/node-sdk`  -> `https://github.com/allthings/node-sdk`  
pip install `allthings-ruby`  -> `https://github.com/allthings/allthings-ruby`  
gem install `allthings-python`  -> `https://github.com/allthings/allthings-python`  

But hey – you got have some good thoughts to I think this discussion can end here.
